window.SOP_DATA = [
  // === KEPERAWATAN MEDIKAL BEDAH (KMB) ===
  {
    id: "kmb-1",
    category: "kmb",
    name: "Pemasangan Infus (IV Line)",
    icon: "fa-syringe",
    color: "blue",
    tools:
      "IV kateter, Infus set, Cairan infus, Tourniquet, Kapas alkohol, Plester, Sarung tangan.",
    steps: [
      "Identifikasi pasien & cuci tangan.",
      "Pasang tourniquet, pilih vena yang lurus & distal.",
      "Desinfeksi sirkuler area penusukan.",
      "Tusukkan jarum sudut 15-30°, cek *flashback* darah.",
      "Tarik mandrin, dorong kateter hingga pangkal.",
      "Sambungkan ke selang infus, cek tetesan.",
      "Fiksasi & beri label tanggal/jam.",
    ],
  },
  {
    id: "kmb-2",
    category: "kmb",
    name: "Pemasangan Kateter Urine",
    icon: "fa-pump-medical",
    color: "emerald",
    tools:
      "Set kateter steril, Urine bag, Jelly steril, Aquadest 10cc, Spuit 10cc, Kapas sublimat/antiseptik, Pinset anatomi.",
    steps: [
      "Vulva/Penis hygiene dengan antiseptik.",
      "Lumuri ujung kateter dengan jelly steril (Pria: 10-15cm, Wanita: 3-5cm).",
      "Masukkan hingga urine keluar, lalu dorong lagi 2-3 cm.",
      "Kembangkan balon kunci dengan Aquadest steril (10cc).",
      "Tarik sedikit untuk memastikan posisi fiksasi.",
    ],
  },
  {
    id: "kmb-3",
    category: "kmb",
    name: "Pemasangan NGT",
    icon: "fa-tube-steel",
    color: "amber",
    tools:
      "Selang NGT, Jelly, Spuit 10-50cc, Stetoskop, Plester, Handuk/Perlak.",
    steps: [
      "Ukur panjang selang (Hidung-Telinga-Prosesus Xipoideus).",
      "Olesi jelly, masukkan lewat hidung saat pasien menelan.",
      "Cek posisi: Aspirasi cairan lambung atau auskultasi udara (Whoosh test).",
      "Fiksasi di hidung dengan plester.",
    ],
  },
  {
    id: "kmb-4",
    category: "kmb",
    name: "Perekaman EKG 12 Lead",
    icon: "fa-heart-pulse",
    color: "rose",
    tools:
      "Mesin EKG, Elektroda (ekstremitas & prekordial), Jelly EKG, Kertas EKG, Kapas alkohol.",
    steps: [
      "Anjurkan pasien tenang & tidak bergerak.",
      "Pasang sadapan ekstremitas (RA, LA, RL, LL).",
      "Pasang elektroda prekordial V1-V6 dengan jelly.",
      "Rekam dan beri identitas pasien pada kertas EKG.",
    ],
  },
  {
    id: "kmb-5",
    category: "kmb",
    name: "Pemberian Transfusi Darah",
    icon: "fa-droplet",
    color: "danger",
    tools:
      "Kantong darah sesuai golongan, Blood set, NaCl 0.9%, Kapas alkohol, Sarung tangan.",
    steps: [
      "Verifikasi kantong darah dengan 2 perawat.",
      "Gunakan blood set & NaCl 0.9% sebagai pembilas.",
      "15 menit pertama tetesan lambat (20 tpm), observasi TTV.",
      "Jika tidak ada reaksi, atur tetesan sesuai instruksi medis.",
    ],
  },
  {
    id: "kmb-6",
    category: "kmb",
    name: "Perawatan Kolostomi",
    icon: "fa-toilet",
    color: "amber",
    tools:
      "Kantong kolostomi baru, Kasa steril, NaCl 0.9%, Zink salep (opsional), Gunting, Sarung tangan.",
    steps: [
      "Lepaskan kantong lama perlahan, observasi fese.",
      "Bersihkan stoma & kulit sekitar dengan NaCl 0.9%.",
      "Ukur diameter stoma & gunting lubang kantong baru (lebihkan 2mm).",
      "Pasang kantong baru, pastikan melekat sempurna tanpa lipatan.",
      "Edukasi pasien tanda-tanda iritasi stoma.",
    ],
  },
  {
    id: "kmb-7",
    category: "kmb",
    name: "Isap Lendir (Suctioning)",
    icon: "fa-wind",
    color: "blue",
    tools:
      "Mesin suction, Kateter suction, Kom berisi NaCl steril, Sarung tangan steril, Masker.",
    steps: [
      "Oksigenasi pasien (Hiperventilasi) 1-2 menit sebelum tindakan.",
      "Gunakan sarung tangan steril, masukkan kateter tanpa menghisap.",
      "Hisap lendir secara intermiten (maksimal 10-15 detik) sambil diputar.",
      "Bilas kateter dengan NaCl, ulangi jika perlu setelah periode istirahat.",
      "Auskultasi suara napas post-tindakan.",
    ],
  },
  {
    id: "kmb-8",
    category: "kmb",
    name: "Pengambilan Darah Vena",
    icon: "fa-vial",
    color: "rose",
    tools:
      "Spuit/Vacutainer, Tourniquet, Kapas alkohol, Plester, Tabung sampel, Sarung tangan.",
    steps: [
      "Pilih vena (biasanya mediana cubiti), pasang tourniquet.",
      "Desinfeksi area dengan alkohol swab secara sirkuler.",
      "Tusuk jarum dengan sudut 15-30°, aspirasi darah sesuai kebutuhan.",
      "Lepas tourniquet sebelum menarik jarum.",
      "Tekan bekas tusukan dengan kapas, beri label pada tabung.",
    ],
  },
  {
    id: "kmb-9",
    category: "kmb",
    name: "Perawatan Luka Post-Operasi",
    icon: "fa-band-aid",
    color: "emerald",
    tools:
      "Set ganti balutan steril, NaCl 0.9%, Antiseptik, Kasa steril, Plester, Sarung tangan.",
    steps: [
      "Buka balutan lama, observasi tanda REEDA (Redness, Edema, Ecchymosis, Discharge, Approximation).",
      "Bersihkan luka dengan teknik steril (dari dalam ke luar).",
      "Oleskan antiseptik jika diperlukan, tutup dengan kasa steril.",
      "Fiksasi dengan plester/perban.",
      "Dokumentasikan kondisi luka dan jumlah drainase.",
    ],
  },
  {
    id: "kmb-10",
    category: "kmb",
    name: "Pemberian Oksigen (Nasal Kanul)",
    icon: "fa-lungs",
    color: "blue",
    tools:
      "Tabung oksigen/sentral, Humidifier (isi air steril), Nasal kanul, Flow meter.",
    steps: [
      "Cek instruksi medis terkait flow rate (biasanya 1-6 Lpm).",
      "Isi humidifier dengan air steril hingga batas marka.",
      "Hubungkan kanul ke humidifier, cek aliran udara pada punggung tangan.",
      "Pasang nasal kanul ke hidung pasien, fiksasi di belakang telinga.",
      "Monitor SpO2 dan kenyamanan hidung pasien.",
    ],
  },
  {
    id: "kmb-11",
    category: "kmb",
    name: "Perawatan Luka Dekubitus",
    icon: "fa-bed",
    color: "rose",
    tools:
      "Cairan NaCl 0.9%, Salep antibiotik/Hydrocolloid, Kasa steril, Gunting nekrotomi (jika perlu), Sarung tangan steril.",
    steps: [
      "Identifikasi stadium luka dekubitus (I-IV).",
      "Cuci luka dengan NaCl 0.9%, lakukan debridemen jaringan mati jika ada.",
      "Oleskan topikal therapy sesuai kondisi luka (basah/kering).",
      "Tutup dengan dressing modern atau kasa steril.",
      "Ubah posisi pasien (Miring kanan-kiri) tiap 2 jam.",
    ],
  },
  {
    id: "kmb-12",
    category: "kmb",
    name: "Pemberian Enema (Huknah)",
    icon: "fa-faucet",
    color: "amber",
    tools:
      "Irigator set, Cairan sabun/Gliserin hangat (37-40\u00b0C), Jelly, Perlak, Selimut mandi.",
    steps: [
      "Atur posisi pasien Sim (miring kiri dengan lutut kanan fleksi).",
      "Isi irigator dengan cairan, keluarkan udara dari selang.",
      "Olesi kanul dengan jelly, masukkan ke anus secara perlahan (7-10 cm).",
      "Alirkan cairan, minta pasien tarik napas dalam.",
      "Anjurkan pasien menahan cairan selama 5-10 menit sebelum BAB.",
    ],
  },
  {
    id: "kmb-13",
    category: "kmb",
    name: "Irigasi Kandung Kemih",
    icon: "fa-droplet-slash",
    color: "blue",
    tools:
      "Cairan Irigasi (NaCl 0.9% 3L), Three-way catheter (terpasang), IV stand, Sarung tangan.",
    steps: [
      "Gantung cairan irigasi pada IV stand, hubungkan ke selang irigasi.",
      "Hubungkan selang ke lumen irigasi pada kateter 3-way.",
      "Atur kecepatan aliran sesuai warna urine (target: rose/jernih).",
      "Monitor input irigasi dan output urine bag (Balance cairan).",
      "Pastikan aliran tidak terhambat untuk mencegah distensi kandung kemih.",
    ],
  },
  {
    id: "kmb-14",
    category: "kmb",
    name: "Pemberian Nutrisi Enteral (NGT Feed)",
    icon: "fa-utensils",
    color: "emerald",
    tools: "Makanan cair/Susu, Air hangat, Spuit 50cc, Stetoskop.",
    steps: [
      "Posisikan pasien fowler/semi-fowler.",
      "Cek residu lambung sebelum memberi makan.",
      "Bilas selang dengan sedikit air hangat.",
      "Alirkan makanan cair secara perlahan menggunakan gaya gravitasi.",
      "Bilas kembali dengan air hangat 30cc, klem selang NGT.",
    ],
  },
  {
    id: "kmb-15",
    category: "kmb",
    name: "Ambulasi Dini (ROM Pasif)",
    icon: "fa-person-walking",
    color: "blue",
    tools: "Bantal penyangga, Handuk.",
    steps: [
      "Lakukan gerakan fleksi & ekstensi pada sendi bahu, siku, dan tangan.",
      "Lakukan gerakan rotasi pada panggul dan lutut.",
      "Lakukan gerakan dorsifleksi & plantarfleksi pada pergelangan kaki.",
      "Ulangi setiap gerakan minimal 5-10 kali.",
      "Observasi respon nyeri dan kelelahan pasien.",
    ],
  },

  // === KEPERAWATAN ANAK ===
  {
    id: "anak-1",
    category: "anak",
    name: "Fisioterapi Dada pada Anak",
    icon: "fa-baby",
    color: "pink",
    tools: "Handuk, Stetoskop, Tissue.",
    steps: [
      "Auskultasi paru untuk mencari letak sekret.",
      "Lakukan *clapping* (menepuk dengan tangan menguncup) selama 3-5 menit.",
      "Lakukan *vibration* (menggetarkan dada) saat pasien ekspirasi.",
      "Lakukan *postural drainage* sesuai area lobus paru yang bermasalah.",
      "Evaluasi suara napas setelah tindakan.",
    ],
  },
  {
    id: "anak-2",
    category: "anak",
    name: "Tepid Sponge (Kompres Hangat)",
    icon: "fa-temperature-empty",
    color: "orange",
    tools:
      "Baskom berisi air hangat (30-35\u00b0C), Waslap (5-6 buah), Termometer, Selimut mandi.",
    steps: [
      "Siapkan air hangat kuku.",
      "Letakkan waslap basah di area axilla dan selangkangan.",
      "Usapkan air hangat ke seluruh tubuh pasien selama 15-20 menit.",
      "Pantau suhu tubuh tiap 15 menit. Hentikan jika suhu turun < 38\u00b0C.",
    ],
  },
  {
    id: "anak-3",
    category: "anak",
    name: "Perawatan Bayi dalam Inkubator",
    icon: "fa-box-open",
    color: "blue",
    tools: "Inkubator (siap pakai), Popok, Termometer bayi.",
    steps: [
      "Atur suhu inkubator sesuai usia dan berat badan bayi.",
      "Pantau suhu tubuh bayi secara berkala (Axilla).",
      "Minimalisir pembukaan pintu inkubator.",
      "Jaga kebersihan inkubator dari cairan tubuh & kotoran.",
    ],
  },
  {
    id: "anak-4",
    category: "anak",
    name: "Fototerapi pada Neonatus",
    icon: "fa-lightbulb",
    color: "amber",
    tools:
      "Lampu fototerapi, Penutup mata bayi (carbon), Pelindung kelamin, Termometer.",
    steps: [
      "Tutup mata & alat kelamin bayi dengan pelindung.",
      "Atur jarak lampu fototerapi (30-50 cm).",
      "Ubah posisi bayi tiap 2-3 jam untuk paparan merata.",
      "Pantau status hidrasi (risiko IWL meningkat).",
    ],
  },
  {
    id: "anak-5",
    category: "anak",
    name: "Pemberian Imunisasi",
    icon: "fa-needle",
    color: "emerald",
    tools: "Vaksin, Spuit AD 0.05 / 0.5cc, Kapas alkohol, Safety box.",
    steps: [
      "Cek *cold chain* (suhu vaksin 2-8\u00b0C).",
      "BCG (Intrakutan), DPT-HB (Intramuskular paha), Polio (Oral).",
      "Gunakan spuit baru & steril untuk setiap suntikan.",
      "Observasi KIPI selama 30 menit.",
    ],
  },
  {
    id: "anak-6",
    category: "anak",
    name: "Pemasangan OGT pada Bayi",
    icon: "fa-baby-carriage",
    color: "blue",
    tools: "Selang OGT (ukuran 5-8 Fr), Spuit 10cc, Stetoskop, Plester, Jelly.",
    steps: [
      "Ukur panjang selang dari mulut ke telinga hingga prosesus xipoideus.",
      "Masukkan selang perlahan melalui mulut bayi.",
      "Cek posisi dengan memasukkan sedikit udara dan dengarkan dengan stetoskop.",
      "Aspirasi cairan lambung untuk memastikan lokasi.",
      "Fiksasi selang di area pipi/mulut dengan plester transparan.",
    ],
  },
  {
    id: "anak-7",
    category: "anak",
    name: "Pengambilan Sampel Darah Tumit",
    icon: "fa-droplet",
    color: "rose",
    tools:
      "Lancet steril, Kapas alkohol, Kertas saring (filter paper), Sarung tangan.",
    steps: [
      "Hangatkan tumit bayi dengan kompres hangat (meningkatkan aliran darah).",
      "Pilih area lateral/medial tumit (hindari area tengah).",
      "Desinfeksi dengan alkohol, biarkan kering.",
      "Tusuk dengan lancet, hapus tetesan pertama.",
      "Teteskan darah ke lingkaran kertas saring hingga meresap sempurna.",
    ],
  },
  {
    id: "anak-8",
    category: "anak",
    name: "Resusitasi Neonatus",
    icon: "fa-heart-circle-bolt",
    color: "danger",
    tools:
      "Meja resusitasi (warmer), Ambubag bayi, Sungkup wajah, Suction, Oksigen.",
    steps: [
      "Lakukan langkah awal: Hangatkan, atur posisi, isap lendir, keringkan, rangsang taktil.",
      "Evaluasi usaha napas dan laju denyut jantung (LDJ).",
      "Jika apnea/megap-megap atau LDJ < 100x/mnt, lakukan VTP (Ventilasi Tekanan Positif).",
      "Jika LDJ < 60x/mnt setelah VTP adekuat, mulai kompresi dada (3:1).",
      "Siapkan epinefrin jika LDJ tetap < 60x/mnt.",
    ],
  },
  {
    id: "anak-9",
    category: "anak",
    name: "Pengukuran Antropometri Anak",
    icon: "fa-ruler-combined",
    color: "emerald",
    tools:
      "Timbangan bayi/anak, Metline (pita ukur), Alat ukur tinggi badan/infantometer.",
    steps: [
      "Timbang berat badan dengan pakaian minimal.",
      "Ukur panjang badan (bayi < 2th terlentang) atau tinggi badan (anak > 2th berdiri).",
      "Ukur Lingkar Kepala (daerah frontal ke oksipital).",
      "Ukur Lingkar Lengan Atas (LiLA) pada titik tengah lengan kiri.",
      "Plot hasil pada grafik pertumbuhan (KMS/WHO Chart).",
    ],
  },
  {
    id: "anak-10",
    category: "anak",
    name: "Perawatan Tali Pusat",
    icon: "fa-scissors",
    color: "pink",
    tools: "Kasa steril, NaCl 0.9% (hanya jika kotor).",
    steps: [
      "Cuci tangan bersih. Bersihkan tali pusat dengan air bersih/NaCl jika terkena tinja.",
      "Keringkan tali pusat dengan kasa bersih.",
      "Lipat popok di bawah tali pusat agar tidak lembap dan terkena urin.",
      "Biarkan tali pusat terbuka (tanpa tutup kasa rapat/gurita).",
      "Edukasi orang tua tanda infeksi (merah, bau, nanah).",
    ],
  },
  {
    id: "anak-11",
    category: "anak",
    name: "Terapi Bermain",
    icon: "fa-gamepad",
    color: "purple",
    tools: "Mainan sesuai usia (Puzzle, Mewarnai, Boneka), Lingkungan aman.",
    steps: [
      "Pilih permainan yang tidak melelahkan fisiknya.",
      "Fasilitasi anak untuk mengekspresikan perasaannya melalui mainan.",
      "Lakukan interaksi terapeutik selama bermain.",
      "Lakukan evaluasi tingkat kecemasan anak (hospitalisasi).",
      "Rapikan alat dan beri apresiasi pada anak.",
    ],
  },
  {
    id: "anak-12",
    category: "anak",
    name: "Kangaroo Mother Care (KMC)",
    icon: "fa-heart",
    color: "rose",
    tools: "Baju KMC/Kain panjang, Topi bayi, Kaos kaki bayi.",
    steps: [
      "Posisikan bayi tegak di dada ibu/ayah (kontak kulit ke kulit).",
      "Posisikan kaki bayi seperti kaki katak (fleksi).",
      "Gunakan pengikat/baju agar bayi tidak merosot.",
      "Pastikan hidung bayi tidak tertekan (bisa bernapas bebas).",
      "Lakukan minimal 1 jam untuk stabilisasi suhu dan bonding.",
    ],
  },
  {
    id: "anak-13",
    category: "anak",
    name: "Screening Tumbuh Kembang (DDST/KPSP)",
    icon: "fa-clipboard-check",
    color: "blue",
    tools: "Formulir KPSP/DDST, Alat peraga (bola, kubus, cermin, dll).",
    steps: [
      "Tentukan usia kronologis anak (hitung bulan/hari).",
      "Tanyakan pertanyaan pada KPSP sesuai kelompok usia.",
      "Minta anak melakukan instruksi (motorik halus/kasar).",
      "Nilai hasil: Sesuai, Meragukan, atau Penyimpangan.",
      "Berikan saran stimulasi jika hasil meragukan.",
    ],
  },
  {
    id: "anak-14",
    category: "anak",
    name: "Pemberian Obat Oral pada Anak",
    icon: "fa-pills",
    color: "amber",
    tools: "Obat (sirup/puyer), Pipet/Sendok takar, Air minum.",
    steps: [
      "Posisikan anak duduk atau setengah duduk (cegah tersedak).",
      "Berikan obat sedikit demi sedikit melalui sisi mulut (pipi dalam).",
      "Tunggu anak menelan sebelum memberikan dosis berikutnya.",
      "Jika anak muntah < 15 menit, konsul untuk pemberian ulang.",
      "Berikan pujian/reward setelah anak mau minum obat.",
    ],
  },
  {
    id: "anak-15",
    category: "anak",
    name: "Pemasangan Infus Anak (Vena Perifer)",
    icon: "fa-syringe",
    color: "blue",
    tools:
      "Abocath ukuran kecil (24-26G), Transfix (plester transparan), Bidai (span spalk), Infus set pediatric.",
    steps: [
      "Cari vena di area dorsalis manus atau pedis.",
      "Lakukan fiksasi kuat karena anak cenderung aktif bergerak.",
      "Gunakan span spalk (bidai) pada area sendi agar infus tidak macet.",
      "Hitung tetesan dengan micro-drip (60 gtt = 1 ml).",
      "Monitor tanda infiltrasi/flebitis lebih sering.",
    ],
  },

  // === KEPERAWATAN MATERNITAS ===
  {
    id: "mat-1",
    category: "maternitas",
    name: "Manuver Leopold (I - IV)",
    icon: "fa-person-breastfeeding",
    color: "pink",
    tools: "Metline (untuk Leopold I), Selimut mandi, Lingkungan tenang.",
    steps: [
      "**Leopold I:** Menentukan TFU dan bagian janin di fundus (Kepala/Bokong).",
      "**Leopold II:** Menentukan letak punggung janin (Punggung/Bagian Kecil).",
      "**Leopold III:** Menentukan bagian terbawah janin (Sudah masuk PAP atau belum).",
      "**Leopold IV:** Konfirmasi seberapa jauh bagian bawah masuk PAP (Divergen/Konvergen).",
    ],
  },
  {
    id: "mat-2",
    category: "maternitas",
    name: "Perawatan Payudara (Post Partum)",
    icon: "fa-hand-holding-heart",
    color: "rose",
    tools: "Kapas, Baby oil/Minyak kelapa, Waslap, Baskom air hangat & dingin.",
    steps: [
      "Kompres puting dengan kapas minyak 2-5 menit.",
      "Lakukan pengurutan payudara sirkuler dari pangkal ke arah puting.",
      "Lakukan gerakan menyilang (cross) untuk merangsang kelenjar susu.",
      "Cuci payudara dengan air hangat dan keringkan.",
    ],
  },
  {
    id: "mat-3",
    category: "maternitas",
    name: "Pemeriksaan Dalam (VT)",
    icon: "fa-fingerprint",
    color: "pink",
    tools:
      "Sarung tangan steril (one hand), Kapas sublimat/DTT, Cairan antiseptik.",
    steps: [
      "Gunakan sarung tangan steril.",
      "Lakukan vulva hygiene.",
      "Masukkan jari tengah & telunjuk secara perlahan.",
      "Nilai pembukaan serviks, ketuban, dan penurunan kepala (Hodge).",
    ],
  },
  {
    id: "mat-4",
    category: "maternitas",
    name: "Memandikan Bayi Baru Lahir",
    icon: "fa-shower",
    color: "rose",
    tools:
      "Bak mandi bayi, Air hangat (37-38\u00b0C), Sabun bayi, Handuk lembut, Pakaian bayi set.",
    steps: [
      "Bersihkan mata, wajah, dan kepala bayi terlebih dahulu.",
      "Gunakan sabun bayi yang lembut, bersihkan dari leher ke bawah.",
      "Bilas dengan air hangat secara hati-hati.",
      "Keringkan segera & lakukan perawatan tali pusat steril.",
    ],
  },
  {
    id: "mat-5",
    category: "maternitas",
    name: "Perawatan Luka Perineum",
    icon: "fa-band-aid",
    color: "pink",
    tools:
      "Kapas DTT/NaCl, Pembalut nifas bersih, Salep/obat (jika diresepkan), Sarung tangan.",
    steps: [
      "Bersihkan area perineum dari depan ke belakang (Uretra-Anus).",
      "Gunakan NaCl 0.9% atau klorheksidin encer.",
      "Keringkan dengan kasa steril, hindari gesekan keras.",
      "Anjurkan pasien ganti pembalut tiap 4 jam atau saat lembap.",
    ],
  },
  {
    id: "mat-6",
    category: "maternitas",
    name: "Senam Hamil",
    icon: "fa-person-running",
    color: "emerald",
    tools: "Matras, Pakaian longgar, Musik relaksasi.",
    steps: [
      "Lakukan pemanasan (gerakan leher, bahu, pinggang).",
      "Latihan pernapasan (napas perut & dada).",
      "Latihan otot panggul & posisi sujud (untuk posisi janin).",
      "Latihan mengejan secara efektif (hanya pada usia kehamilan aterm).",
      "Relaksasi akhir (pendinginan).",
    ],
  },
  {
    id: "mat-7",
    category: "maternitas",
    name: "Inisiasi Menyusu Dini (IMD)",
    icon: "fa-baby",
    color: "rose",
    tools: "Topi bayi, Selimut kering, Ibu dalam posisi rileks (baring).",
    steps: [
      "Keringkan tubuh bayi kecuali kedua tangannya.",
      "Tengkurapkan bayi di dada ibu supaya ada kontak kulit.",
      "Biarkan bayi mencari puting susu ibu sendiri selama minimal 1 jam.",
      "Selimuti ibu dan bayi serta beri topi pada bayi.",
      "Monitor pernapasan dan suhu bayi selama proses.",
    ],
  },
  {
    id: "mat-8",
    category: "maternitas",
    name: "Pijat Oksitosin",
    icon: "fa-hand-holding",
    color: "pink",
    tools: "Minyak pijat, Ibu duduk bersandar ke depan pada meja.",
    steps: [
      "Posisikan ibu duduk bersandar ke depan dengan kedua tangan di atas meja.",
      "Lakukan pemijatan pada kedua sisi tulang belakang menggunakan ibu jari.",
      "Gerakan melingkar kecil dimulai dari leher ke arah tulang belikat (skapula).",
      "Lakukan selama 2-3 menit untuk merangsang refleks let-down ASI.",
      "Evaluasi perasaan ibu (harus merasa rileks).",
    ],
  },
  {
    id: "mat-9",
    category: "maternitas",
    name: "Penanganan Perdarahan Postpartum (KBI/KBE)",
    icon: "fa-shield-virus",
    color: "danger",
    tools:
      "Sarung tangan panjang (obstetrik), Cairan infus (RL/Oxytocin), Kateter urine.",
    steps: [
      "**Kompresi Bimanual Interna (KBI):** Tangan masuk ke vagina, mengepal fornix anterior, tangan luar menekan fundus.",
      "Tahan selama 5 menit hingga uterus berkontraksi.",
      "Ajarkan keluarga **Kompresi Bimanual Eksterna (KBE)** meletakkan tangan di abdomen.",
      "Berikan uterotonika (Oxytocin/Misoprostol) sesuai instruksi.",
      "Jika gagal, siapkan tamponade uterus atau rujukan pembedahan.",
    ],
  },
  {
    id: "mat-10",
    category: "maternitas",
    name: "Pemeriksaan Fisik Ibu Hamil (ANC)",
    icon: "fa-stethoscope",
    color: "blue",
    tools: "Tensimeter, Timbangan, Metline, Doppler, Monoral (Laennec).",
    steps: [
      "Timbang BB & Ukur Tekanan Darah.",
      "Ukur TFU (Tinggi Fundus Uteri) untuk estimasi usia kehamilan.",
      "Lakukan manuver Leopold I-IV.",
      "Dengarkan DJJ (Denyut Jantung Janin) dengan doppler.",
      "Cek adanya edema pada ekstremitas/wajah.",
    ],
  },
  {
    id: "mat-11",
    category: "maternitas",
    name: "Pemasangan IUD",
    icon: "fa-anchor",
    color: "purple",
    tools:
      "Kit IUD (Copper T), Spekulum Sims, Tenakulum, Sonde uterus, Gunting benang, Kasa & antiseptik.",
    steps: [
      "Pemeriksaan bimanual untuk cek posisi & besar uterus.",
      "Pasang spekulum & lakukan desinfeksi portio.",
      "Ukur panjang uterus dengan sonde (minimal 6-9 cm).",
      "Masukkan inserter IUD hingga mencapai fundus.",
      "Gunting benang IUD sisakan 2-3 cm dari ostium uteri.",
    ],
  },
  {
    id: "mat-12",
    category: "maternitas",
    name: "Pijat Endorphin (Pereda Nyeri Persalinan)",
    icon: "fa-spa",
    color: "emerald",
    tools: "Minyak aromaterapi, Suasana tenang.",
    steps: [
      "Minta ibu tarik napas dalam & rileks.",
      "Sentuh permukaan kulit sepanjang lengan atau punggung dengan ujung jari sangat lembut.",
      "Bentuk pola seperti huruf 'V' terbalik di punggung dari leher ke bawah.",
      "Lakukan dorongan afirmasi positif kepada ibu.",
      "Evaluasi tingkat kenyamanan & penurunan skala nyeri.",
    ],
  },
  {
    id: "mat-13",
    category: "maternitas",
    name: "Pemberian Magnesium Sulfat (MgSO4) pada Pre-eklamsia",
    icon: "fa-vial",
    color: "rose",
    tools:
      "MgSO4 40%, Syringe Pump, Kalsium Glukonat (Antidotum), Kateter urine.",
    steps: [
      "Cek syarat: RR > 16x, Refleks patella (+), Urin > 30ml/jam.",
      "Berikan dosis loading (4 gram) secara IV perlahan (15-20 menit).",
      "Lanjutkan dosis rumatan lewat infus/syringe pump.",
      "Monitor TTV dan status mental tiap jam.",
      "Siapkan Kalsium Glukonat jika terjadi tanda intoksikasi (apnea).",
    ],
  },
  {
    id: "mat-14",
    category: "maternitas",
    name: "Vulva Hygiene Postpartum",
    icon: "fa-hand-sparkles",
    color: "pink",
    tools: "Kapas DTT, Air bersih, Perlak.",
    steps: [
      "Bantu ibu posisi dorsal recumbent.",
      "Bersihkan labia mayora/minora dari atas ke bawah.",
      "Bersihkan area perineum hingga anus.",
      "Observasi lokia (warna, jumlah, bau).",
      "Pastikan area genital kering sebelum memakai pembalut.",
    ],
  },
  {
    id: "mat-15",
    category: "maternitas",
    name: "Perawatan Luka Sectio Caesarea (SC)",
    icon: "fa-bandage",
    color: "blue",
    tools: "Set ganti balut steril, NaCl, Kasa, Plester anti-air.",
    steps: [
      "Buka balutan lama, observasi integritas jahitan.",
      "Bersihkan luka dengan kasa NaCl secara lembut.",
      "Pastikan luka tidak basah (rembesan).",
      "Tutup dengan dressing modern agar ibu bisa segera mandi.",
      "Edukasi ibu untuk tidak mengangkat beban berat.",
    ],
  },

  // === KEPERAWATAN JIWA ===
  {
    id: "jiwa-1",
    category: "jiwa",
    name: "Komunikasi Terapeutik (SP Pasien)",
    icon: "fa-comments",
    color: "purple",
    tools: "Catatan keperawatan (Status), Lingkungan yang tenang/private.",
    steps: [
      "Fase Pra-interaksi: Evaluasi diri & siapkan data pasien.",
      "Fase Orientasi: Salam, kontrak waktu, tujuan interaksi.",
      "Fase Kerja: Tanyakan keluhan, dengarkan aktif, ajarkan strategi koping.",
      "Fase Terminasi: Evaluasi perasaan pasien, rencana tindak lanjut.",
    ],
  },
  {
    id: "jiwa-2",
    category: "jiwa",
    name: "Manajemen Restrain / Pengikatan",
    icon: "fa-user-lock",
    color: "purple",
    tools:
      "Tali restrain kain empuk, Tempat tidur dengan pengunci, Sarung tangan.",
    steps: [
      "Indikasi: Gaduh gelisah & risiko mencederai diri/orang lain.",
      "Lakukan intervensi verbal/obat dulu, jika gagal baru restrain.",
      "Ikat pergelangan dengan simpul yang mudah dilepas (quick release).",
      "Observasi sirkulasi peripheral dan posisi tiap 15-30 menit.",
    ],
  },
  {
    id: "jiwa-3",
    category: "jiwa",
    name: "Terapi Aktivitas Kelompok (TAK)",
    icon: "fa-users",
    color: "purple",
    tools: "Papan nama peserta, Bola/musik, Lembar evaluasi.",
    steps: [
      "Pilih anggota kelompok dengan masalah yang sama.",
      "Lead: Lead, Co-lead, Fasilitator, dan Observer.",
      "Latih kemampuan sosialisasi atau persepsi sensori.",
      "Evaluasi kemampuan pasien dalam memberikan feedback kelompok.",
    ],
  },
  {
    id: "jiwa-4",
    category: "jiwa",
    name: "Manejemen Halusinasi (SP 1)",
    icon: "fa-ear-listen",
    color: "purple",
    tools: "Media edukasi halusinasi.",
    steps: [
      "Bantu pasien mengenali jenis, isi, waktu, dan frekuensi halusinasi.",
      'Ajarkan cara menghardik: "Pergi kamu, kamu suara palsu!" sambil menutup telinga.',
      "Minta pasien memperagakan cara yang diajarkan.",
      "Masukkan ke dalam jadwal kegiatan harian pasien.",
    ],
  },
  {
    id: "jiwa-5",
    category: "jiwa",
    name: "Discharge Planning Jiwa",
    icon: "fa-house-user",
    color: "purple",
    tools: "Leaflet kepatuhan obat, Nomor faskes rujukan.",
    steps: [
      "Edukasi keluarga tentang tanda kekambuhan (relapse).",
      "Jelaskan prinsip 5 Benar pemberian obat di rumah.",
      "Latih keluarga cara merawat ADL pasien.",
      "Berikan jadwal kontrol rutin ke RSJ/Poli Jiwa.",
    ],
  },
  {
    id: "jiwa-6",
    category: "jiwa",
    name: "SP 1 Pasien Risiko Perilaku Kekerasan (RPK)",
    icon: "fa-angry",
    color: "danger",
    tools: "Bantal (untuk penyaluran energi marah).",
    steps: [
      "Identifikasi penyebab marah, tanda, dan akibat dari marahnya.",
      "Latih cara fisik 1 (Tarik napas dalam) saat emosi naik.",
      "Latih cara fisik 2 (Pukul bantal/kasur) untuk menyalurkan energi.",
      "Buat jadwal latihan cara fisik harian.",
      "Evaluasi penurunan dorongan menyerang/marah.",
    ],
  },
  {
    id: "jiwa-7",
    category: "jiwa",
    name: "SP 1 Pasien Harga Diri Rendah (HDR)",
    icon: "fa-user-slash",
    color: "amber",
    tools: "Kertas & Pulpen (untuk daftar kemampuan).",
    steps: [
      "Identifikasi aspek positif dan kemampuan yang masih dimiliki.",
      "Minta pasien memilih satu kemampuan yang ingin dilatih.",
      "Latih kemampuan yang dipilih (mis: merapikan tempat tidur).",
      "Beri pujian yang tulus atas keberhasilan pasien.",
      "Masukkan kegiatan ke dalam jadwal harian.",
    ],
  },
  {
    id: "jiwa-8",
    category: "jiwa",
    name: "SP 1 Pasien Defisit Perawatan Diri (DPD)",
    icon: "fa-soap",
    color: "blue",
    tools: "Alat mandi (Sabun, Sikat gigi, Shampo, Handuk).",
    steps: [
      "Identifikasi masalah kebersihan diri: mandi, berhias, BAB/BAK.",
      "Jelaskan pentingnya kebersihan diri untuk harga diri & kesehatan.",
      "Latih cara mandi dan berhias secara benar.",
      "Minta pasien mempraktekkan (simulasi) langkah mandi.",
      "Masukkan kegiatan mandi ke jadwal rutin pagi dan sore.",
    ],
  },
  {
    id: "jiwa-9",
    category: "jiwa",
    name: "SP 1 Pasien Waham",
    icon: "fa-brain",
    color: "purple",
    tools: "Objek kebenaran (mis: Jam kanti, Kalender).",
    steps: [
      "Bina hubungan saling percaya (jangan membantah waham).",
      "Bantu pasien melakukan orientasi realita (siapa, dimana, kapan).",
      "Identifikasi kebutuhan pasien yang belum terpenuhi melalui wahamnya.",
      "Latih kemampuan positif yang masih bisa dilakukan pasien.",
      "Masukkan ke jadwal harian untuk mengalihkan pikiran waham.",
    ],
  },
  {
    id: "jiwa-10",
    category: "jiwa",
    name: "Pengkajian Status Mental",
    icon: "fa-clipboard-list",
    color: "blue",
    tools: "Format kuesioner MSE (Mental Status Exam).",
    steps: [
      "Amati penampilan (rapi/berantakan) dan aktivitas motorik.",
      "Nilai pembicaraan (cepat/lambat) dan alam perasaan (mood/afek).",
      "Nilai proses pikir (arus, bentuk, isi pikir seperti waham).",
      "Cek tingkat kesadaran dan daya ingat (memori).",
      "Simpulkan tingkat kemandirian dan mekanisme koping.",
    ],
  },
  {
    id: "jiwa-11",
    category: "jiwa",
    name: "Terapi Psikopsikofarmaka (Edukasi Obat)",
    icon: "fa-pills",
    color: "rose",
    tools: "Contoh wadah obat CPZ, HLP, THP.",
    steps: [
      "Jelaskan manfaat obat penenang dan obat pengontrol emosi.",
      "Edukasi efek samping: Mulut kering (minum banyak), Mengantuk, Mata melirik atas.",
      "Sampaikan pentingnya tidak menghentikan obat tanpa konsultasi dokter.",
      "Latih teknik 8 Benar obat: Pasien, Obat, Dosis, Rute, Waktu, Cara, Dokumentasi, Manfaat.",
      "Pastikan obat benar-benar ditelan oleh pasien di depan perawat.",
    ],
  },
  {
    id: "jiwa-12",
    category: "jiwa",
    name: "Manajemen Krisis (Percobaan Bunuh Diri)",
    icon: "fa-shield-heart",
    color: "danger",
    tools: "Lingkungan bersih dari benda tajam/tali/obat.",
    steps: [
      "Pastikan keamanan lingkungan (Singkirkan benda berbahaya).",
      "Lakukan pengawasan ketat (Observasi 1:1 jika perlu).",
      "Bina hubungan saling percaya dengan tulus (Empati).",
      "Bantu pasien mengidentifikasi alasan untuk hidup.",
      "Berikan dorongan untuk mengekspresikan perasaan secara verbal.",
    ],
  },
  {
    id: "jiwa-13",
    category: "jiwa",
    name: "Terapi Lingkungan (Milieu Therapy)",
    icon: "fa-campground",
    color: "emerald",
    tools: "Area terbuka (taman/teras), Jadwal kegiatan bangsal.",
    steps: [
      "Ciptakan lingkungan fisik yang aman dan suportif.",
      "Libatkan pasien dalam struktur harian (makan bersama, olahraga pagi).",
      "Terapkan tata tertib bangsal secara konsisten namun fleksibel.",
      "Fasilitasi interaksi sosial antar pasien yang sehat.",
      "Evaluasi adaptasi pasien terhadap lingkungan baru.",
    ],
  },
  {
    id: "jiwa-14",
    category: "jiwa",
    name: "Latihan Asertif",
    icon: "fa-bullhorn",
    color: "blue",
    tools: "Dialog simulasi (roleplay).",
    steps: [
      "Identifikasi situasi dimana pasien sulit berkata 'Tidak'.",
      "Ajarkan teknik menyampaikan keinginan tanpa marah atau takut.",
      "Latih kontak mata dan nada suara yang tegas namun tenang.",
      "Roleplay: Menyatakan ketidaksediaan terhadap ajakan negatif.",
      "Beri reinforcement positif saat pasien berani asertif.",
    ],
  },
  {
    id: "jiwa-15",
    category: "jiwa",
    name: "Terapi Senam Jiwa",
    icon: "fa-music",
    color: "orange",
    tools: "Audio musik semangat, Pemandu senam.",
    steps: [
      "Kumpulkan pasien di lapangan/aula yang luas.",
      "Lakukan gerakan pemanasan mengikuti irama musik.",
      "Gerakan inti: Melibatkan koordinasi tangan, kaki, dan pernapasan.",
      "Gerakan pendinginan: Tarik napas bersama dan saling memberi semangat.",
      "Evaluasi perasaan pasien (biasanya merasa lebih segar/bahagia).",
    ],
  },

  // === GAWAT DARURAT (GADAR) ===
  {
    id: "gadar-1",
    category: "gadar",
    name: "Bantuan Hidup Dasar (BHD / RJP)",
    icon: "fa-heart-circle-bolt",
    color: "danger",
    tools: "Manekin RJP (jika latihan), Masker, Sarung tangan.",
    steps: [
      "Cek respon & panggil bantuan (Activate Code Blue).",
      "Cek nadi karotis & napas (< 10 detik).",
      "Jika tidak ada nadi: Kompresi 30 kali (Kedalaman 5-6 cm).",
      "Buka jalan napas, berikan 2x napas buatan.",
      "Lakukan 5 siklus (30:2) sebelum re-evaluasi.",
    ],
  },
  {
    id: "gadar-2",
    category: "gadar",
    name: "Pembidaian (Splinting)",
    icon: "fa-bandage",
    color: "danger",
    tools: "Bidai (spalk), Mitella/Perban, Kasa.",
    steps: [
      "Lakukan PMS (Pulse, Motorik, Sensorik) sebelum pembidaian.",
      "Pilih bidai yang kaku dan melewati dua sendi.",
      "Ikat bidai dengan stabil tapi tidak menghambat sirkulasi.",
      "Lakukan PMS kembali setelah pembidaian.",
    ],
  },
  {
    id: "gadar-3",
    category: "gadar",
    name: "Balut Tekan (Control Bleeding)",
    icon: "fa-hand-holding-medical",
    color: "danger",
    tools: "Kasa tebal, Perban elastis, Sarung tangan.",
    steps: [
      "Identifikasi sumber perdarahan.",
      "Lakukan tekanan langsung dengan kasa tebal di atas luka.",
      "Bebat secara sirkular menggunakan elastis perban.",
      "Jika tembus, tambahkan kasa baru di atasnya (jangan lepas yang lama).",
    ],
  },
  {
    id: "gadar-4",
    category: "gadar",
    name: "Pemasangan OPA / Mayo (Guedel)",
    icon: "fa-mask",
    color: "danger",
    tools: "OPA (ukuran yang sesuai), Sudip lidah (tongue spatel).",
    steps: [
      "Ukur ukuran OPA (Sudut mulut ke angulus mandibula).",
      "Buka mulut, masukkan dengan lengkungan menghadap ke palatum.",
      "Putar 180\u00b0 setelah melewati pangkal lidah.",
      "Hentikan jika ada refleks muntah.",
    ],
  },
  {
    id: "gadar-5",
    category: "gadar",
    name: "Triage Tagging (START)",
    icon: "fa-tags",
    color: "danger",
    tools: "Kartu Triage (Merah, Kuning, Hijau, Hitam), Jam tangan.",
    steps: [
      "Nilai Respirasi (Napas > 30x/mnt = Merah).",
      "Nilai Perfusi (CRT > 2 detik = Merah).",
      "Nilai Status Mental (Tidak bisa ikut perintah = Merah).",
      "Beri label warna sesuai hasil pemeriksaan cepat.",
    ],
  },
  {
    id: "gadar-6",
    category: "gadar",
    name: "Pemasangan Collar Neck",
    icon: "fa-grip-lines",
    color: "blue",
    tools: "Collar neck (rigid) sesuai ukuran, 2 perawat.",
    steps: [
      "Perawat 1: Lakukan manual in-line stabilization (pegang kepala).",
      "Perawat 2: Ukur lebar leher pasien (jari) sesuai alat.",
      "Pasang bagian belakang collar terlebih dahulu.",
      "Kunci bagian depan tepat di bawah dagu.",
      "Pastikan posisi kepala netral dan stabil.",
    ],
  },
  {
    id: "gadar-7",
    category: "gadar",
    name: "Kumbah Lambung (Gastric Lavage)",
    icon: "fa-faucet",
    color: "blue",
    tools:
      "Selang NGT besar, Cairan bilas (300-500ml), Wadah penampung, Spuit 50cc.",
    steps: [
      "Pastikan jalan napas aman (resiko aspirasi).",
      "Masukkan selang NGT ke lambung, cek posisi.",
      "Masukkan cairan bilas, biarkan 1 menit.",
      "Aspirasi atau alirkan balik hingga cairan keluar jernih.",
      "Observasi adanya darah atau bau zat kimia pada cairan keluar.",
    ],
  },
  {
    id: "gadar-8",
    category: "gadar",
    name: "Heimlich Maneuver (Choking)",
    icon: "fa-user-nurse",
    color: "danger",
    tools: "Tidak ada (Tangan kosong).",
    steps: [
      "Berdiri di belakang pasien, lingkarkan tangan ke perutnya.",
      "Kepalkan satu tangan di antara pusar dan ulu hati.",
      "Lakukan dorongan ke dalam dan ke atas (upward thrust) secara kuat.",
      "Ulangi hingga benda asing keluar atau pasien tidak sadar.",
      "Jika tidak sadar, segera mulai RJP.",
    ],
  },
  {
    id: "gadar-9",
    category: "gadar",
    name: "Penanganan Luka Bakar Akut",
    icon: "fa-fire",
    color: "orange",
    tools: "Cairan infus RL hangat, Kasa NaCl, Salep silver sulfadiazine.",
    steps: [
      "Hentikan proses pembakaran (Stop, Drop, Roll/Air mengalir).",
      "Lakukan survey primer (A-B-C) terutama jika ada luka bakar inhalasi.",
      "Guyur area luka dengan air mengalir (bukan es) selama 20 menit.",
      "Hitung luas luka (Rule of Nines) & resusitasi cairan (Formula Baxter).",
      "Tutup luka dengan kasa steril lembap atau salep antibiotik burn.",
    ],
  },
  {
    id: "gadar-10",
    category: "gadar",
    name: "Evakuasi Log Roll",
    icon: "fa-users-viewfinder",
    color: "blue",
    tools: "Long Spine Board (LSB), Strap pengikat, 3-4 perawat.",
    steps: [
      "Leader memegang kepala/lehir (in-line stabilization).",
      "Perawat lain berjejer di satu sisi tubuh pasien.",
      "Miringkan pasien satu komando (seperti balok kayu).",
      "Sisipkan LSB di bawah punggung, kembalikan posisi supine.",
      "Ikat pasien ke LSB dengan strap agar tidak bergeser.",
    ],
  },
  {
    id: "gadar-11",
    category: "gadar",
    name: "Pemasangan Mayo (OPA) pada Pasien Tidak Sadar",
    icon: "fa-mask-ventilator",
    color: "blue",
    tools: "Guedel/OPA, Suction.",
    steps: [
      "Bersihkan mulut dari sisa makanan/muntahan dengan suction.",
      "Pilih ukuran OPA dari sudut bibir ke daun telinga.",
      "Masukkan dengan lengkungan terbalik ke langit-langit.",
      "Putar 180 derajat setelah setengah masuk.",
      "Pastikan lidah tertahan dan udara bisa lewat.",
    ],
  },
  {
    id: "gadar-12",
    category: "gadar",
    name: "Manajemen Syok Hipovolemik",
    icon: "fa-droplet-slash",
    color: "danger",
    tools:
      "IV catheter ukuran besar (16-18G), Cairan Kristaloid (RL), Tensimeter.",
    steps: [
      "Posisikan pasien Shock Position (Kaki lebih tinggi 30-45 derajat).",
      "Pasang 2 jalur IV line sekaligus untuk guyur cairan.",
      "Berikan loading cairan sesuai estimasi kehilangan (biasanya 20ml/kgBB).",
      "Pantau produksi urin (minimal 0.5cc/kgBB/jam).",
      "Evaluasi perbaikan nadi dan saturasi oksigen.",
    ],
  },
  {
    id: "gadar-13",
    category: "gadar",
    name: "Penanganan Gigitan Ular (Snake Bite)",
    icon: "fa-disease",
    color: "danger",
    tools: "Spalk, Mitella, Anti Bisa Ular (ABU).",
    steps: [
      "Istirahatkan total area yang digigit (Imobilisasi).",
      "Pasang bidai agar sendi tidak bergerak sama sekali (mencegah penyebaran bisa via limfe).",
      "Jangan lakukan sayatan, hisapan, atau torniket terlalu kencang.",
      "Monitor pembengkakan, nyeri, dan gejala sistemik (kelumpuhan).",
      "Persiapkan ABU jika ada tanda vaskulotoksik/neurotoksik.",
    ],
  },
  {
    id: "gadar-14",
    category: "gadar",
    name: "Needle Decompression (Tension Pneumothorax)",
    icon: "fa-syringe",
    color: "danger",
    tools: "Abocath besar (14G), Kapas alkohol.",
    steps: [
      "Identifikasi tanda Tension Pneumothorax (Deviasi trakea, Vena jugularis distensi, Hipotensi).",
      "Cari area Intercostal Space (ICS) ke-2 di garis Mid-Clavicular.",
      "Tusukkan jarum tegak lurus hingga terdengar bunyi 'his' udara keluar.",
      "Biarkan jarum terpasang sebagai kateter sementara.",
      "Persiapkan pemasangan Chest Tube/WSD segera.",
    ],
  },
  {
    id: "gadar-15",
    category: "gadar",
    name: "Pemasangan Syringe Pump",
    icon: "fa-microchip",
    color: "blue",
    tools:
      "Syringe pump machine, Spuit 50cc, Obat (mis: Dopamine/Norepi), Ekstension tube.",
    steps: [
      "Encerkan obat sesuai dosis dan instruksi dokter.",
      "Keluarkan udara dari spuit dan ekstension tube.",
      "Pasang spuit pada mesin syringe pump secara tepat.",
      "Atur kecepatan aliran (ml/jam) sesuai rumus titrasi.",
      "Hubungkan ke IV line pasien & tekan 'Start'.",
    ],
  },
];
